### ISSUE TITLE
Spring Gateway와 Eureka Server 연동 및 테스트

### ISSUE THREAD

**Issue by Mingyum-Kim** [Mingyum-Kim/Iamhere#32]
#31 에 이어서 작업한다. 
Spring Gateway에서 넘겨받은 요청을 Eureka Server가 이벤트를 감지하고 로드밸런싱한다. 

추가로, Gateway 서버를 AWS 서버로 옮겨서 동작한다.

**Comment by Mingyum-Kim** [comment]
apigateway의 application.yml의 routing uri을 아래와 같이 작성하여 유레카에서 gateway의 이벤트를 탐지할 수 있도록 한다.
```
 # MEMBER 서비스 설정
        - id: svc-member # 정책명
          uri: lb://localhost:8080 # 유레카에 등록된 서비스로 라우팅
          predicates:
            - Path=/api/v1/members/**
```
lb는 LoadBalancing의 약자이다. 이를 통해 여러 서비스에 동적으로 라우팅이 가능하다. 

![image](https://github.com/Mingyum-Kim/Iamhere/assets/67851124/8f8a5bea-8ed1-4087-ab1b-2c91dc82649e)
위와 같이 마이크로서비스와 그것들을 라우팅하는 역할을 하는 API gateway가 Eureka Server에 감지되면 연동 성공이다.
